name: Team awesome's approval workflow
on: pull_request_review

jobs:
    labelWhenApproved:
        runs-on: ubuntu-latest
        steps:
        - name: any name you wish
        - uses: pullreminders/label-when-approved-action
          env:
            APPROVALS: 1
            GITHUB_TOKEN: ${{secrets.GITHUB-TOKEN}}
            ADD_LABEL: "Approved label "
